
#HomePage
sign_in_button = 'div.header_right.d-flex.align-items-center button:nth-of-type(2)'
guest_log_in_button = 'div.header_right.d-flex.align-items-center button.header-link.-guest'
sign_up_button = 'div.hero-descriptor button.hero-descriptor_btn.btn.btn-primary'
email_button = 'a.contacts_link.h4'
hillel_button = 'a.contacts_link.display-4'
all_icons_of_social = 'div.contacts_socials.socials'
instructions_and_manuals = 'div.col-12.col-lg-6.mt-lg-0.mt-md-5.mt-sm-4.mt-3'
button_about = 'button.btn.header-link[appscrollto="aboutSection"]'
button_contacts = 'button.btn.header-link[appscrollto="contactsSection"]'
main_button = 'div.header_left.d-flex.align-items-center a.header_logo'
button_home = 'div.header_left.d-flex.align-items-center a.btn.header-link.-active'
facebook_button = 'div.contacts_socials.socials span.socials_icon.icon.icon-facebook'
telegram_button = 'div.contacts_socials.socials span.socials_icon.icon.icon-telegram'
youtube_button = 'div.contacts_socials.socials span.socials_icon.icon.icon-youtube'
instagram_button = 'div.contacts_socials.socials span.socials_icon.icon.icon-instagram'
linkedin_button = 'div.contacts_socials.socials span.socials_icon.icon.icon-linkedin'
hillel_button_in_footer = 'div.col.footer_item.-right svg'
video_from_youtube = 'iframe.hero-video_frame'

#LogInModalWindow
email_input_field = 'input.form-control.ng-untouched.ng-pristine.ng-invalid[id="signinEmail"]'
password_input_field = 'input.form-control.ng-untouched.ng-pristine.ng-invalid[id="signinPassword"]'
button_remember_me = 'input.form-check-input.ng-untouched.ng-pristine.ng-valid[id="remember"]'
button_forgot_password = 'div.form-group.d-flex.align-items-center.justify-content-between button.btn.btn-link'
button_registration = 'div.modal-footer.d-flex.justify-content-between button.btn.btn-link'
button_login = 'div.modal-footer.d-flex.justify-content-between button.btn.btn-primary'
button_close_modal_window = 'button.close span'
