
#HomePage
sign_in_button = '//div[@class="header_right d-flex align-items-center"]//button[2]'
guest_log_in_button = '//div[@class="header_right d-flex align-items-center"]//button[@class="header-link -guest"]'
sign_up_button = '//div[@class="hero-descriptor"]//button[@class="hero-descriptor_btn btn btn-primary"]'
email_button = '//a[@class="contacts_link h4"]'
hillel_button = '//a[@class="contacts_link display-4"]'
all_icons_of_social = '//div[@class="contacts_socials socials"]'
log_fuel_expenses = '//div[@class="col-12 col-lg-6"]'
button_about = '//button[@class="btn header-link" and @appscrollto="aboutSection"]'
button_contacts = '//button[@class="btn header-link" and @appscrollto="contactsSection"]'
main_button = '//div[@class="header_left d-flex align-items-center"]//a[@class="header_logo"]'
button_home = '//div[@class="header_left d-flex align-items-center"]//a[@class="btn header-link -active"]'
facebook_button = '//div[@class="contacts_socials socials"]//span[@class="socials_icon icon icon-facebook"]'
telegram_button = '//div[@class="contacts_socials socials"]//span[@class="socials_icon icon icon-telegram"]'
youtube_button = '//div[@class="contacts_socials socials"]//span[@class="socials_icon icon icon-youtube"]'
instagram_button = '//div[@class="contacts_socials socials"]//span[@class="socials_icon icon icon-instagram"]'
linkedin_button = '//div[@class="contacts_socials socials"]//span[@class="socials_icon icon icon-linkedin"]'
hillel_button_in_footer = '//div[@class="col footer_item -right"]//*[name()="svg"]'
video_from_youtube = '//iframe[@class="hero-video_frame"]'

#LogInModalWindow
email_input_field = '//input[@class="form-control ng-untouched ng-pristine ng-invalid" and @id="signinEmail"]'
password_input_field = '//input[@class="form-control ng-untouched ng-pristine ng-invalid" and @id="signinPassword"]'
button_remember_me = '//input[@class="form-check-input ng-untouched ng-pristine ng-valid" and @id="remember"]'
button_forgot_password = '//div[@class="form-group d-flex align-items-center justify-content-between"]//button[@class="btn btn-link"]'
button_registration = '//div[@class="modal-footer d-flex justify-content-between"]//button[@class="btn btn-link"]'
button_login = '//button[@class="btn btn-primary"]'
button_close_modal_window = '//button[@class="close"]//span'